 name: NIX-OPS-Pre-Maintenance Patching
  remote_user: ansible
  hosts: all
  become: true
  ignore_errors: yes

  tasks:
    - name: Check RHN or local repository connectivity
      shell:
        cmd: yum repolist  > /dev/null 2>&1; if [ $? -eq 0 ]; then echo "Repository found"; else echo "No repository found"; fi
      register: repo_status
                      
    - name: Failed if no repository found
      fail:
        msg: "repository not found on {{ ansible_hostname }}"
      when: repo_status.stdout != "Repository found"
                                                                  
   
